let countries = [
{iso_code:  "us", id: "1", text: "USA", country_code: "+1"},
{iso_code:  "gb", id: "44", text: "UK", country_code: "+44"},
{iso_code:  "dz", id: "213", text: "Algeria", country_code: "+213"},
{iso_code:  "ad", id: "376", text: "Andorra", country_code: "+376"},
{iso_code:  "ao", id: "244", text: "Angola", country_code: "+244"},
{iso_code:  "ai", id: "1264", text: "Anguilla", country_code: "+1264"},
{iso_code:  "ag", id: "1268", text: "Antigua & Barbuda", country_code: "+1268"},
{iso_code:  "ar", id: "54", text: "Argentina", country_code: "+54"},
{iso_code:  "am", id: "374", text: "Armenia", country_code: "+374"},
{iso_code:  "aw", id: "297", text: "Aruba", country_code: "+297"},
{iso_code:  "au", id: "61", text: "Australia", country_code: "+61"},
{iso_code:  "at", id: "43", text: "Austria", country_code: "+43"},
{iso_code:  "az", id: "994", text: "Azerbaijan", country_code: "+994"},
{iso_code:  "bs", id: "1242", text: "Bahamas", country_code: "+1242"},
{iso_code:  "bh", id: "973", text: "Bahrain", country_code: "+973"},
{iso_code:  "bd", id: "880", text: "Bangladesh", country_code: "+880"},
{iso_code:  "bb", id: "1246", text: "Barbados", country_code: "+1246"},
{iso_code:  "by", id: "375", text: "Belarus", country_code: "+375"},
{iso_code:  "be", id: "32", text: "Belgium", country_code: "+32"},
{iso_code:  "bz", id: "501", text: "Belize", country_code: "+501"},
{iso_code:  "bj", id: "229", text: "Benin", country_code: "+229"},
{iso_code:  "bm", id: "1441", text: "Bermuda", country_code: "+1441"},
{iso_code:  "bt", id: "975", text: "Bhutan", country_code: "+975"},
{iso_code:  "bo", id: "591", text: "Bolivia", country_code: "+591"},
{iso_code:  "ba", id: "387", text: "Bosnia Herzegovina", country_code: "+387"},
{iso_code:  "bw", id: "267", text: "Botswana", country_code: "+267"},
{iso_code:  "br", id: "55", text: "Brazil", country_code: "+55"},
{iso_code:  "bn", id: "673", text: "Brunei", country_code: "+673"},
{iso_code:  "bg", id: "359", text: "Bulgaria", country_code: "+359"},
{iso_code:  "bf", id: "226", text: "Burkina Faso", country_code: "+226"},
{iso_code:  "bi", id: "257", text: "Burundi", country_code: "+257"},
{iso_code:  "kh", id: "855", text: "Cambodia", country_code: "+855"},
{iso_code:  "cm", id: "237", text: "Cameroon", country_code: "+237"},
{iso_code:  "ca", id: "1", text: "Canada", country_code: "+1"},
{iso_code:  "cv", id: "238", text: "Cape Verde Islands", country_code: "+238"},
{iso_code:  "ky", id: "1345", text: "Cayman Islands", country_code: "+1345"},
{iso_code:  "cf", id: "236", text: "Central African Republic", country_code: "+236"},
{iso_code:  "cl", id: "56", text: "Chile", country_code: "+56"},
{iso_code:  "cn", id: "86", text: "China", country_code: "+86"},
{iso_code:  "co", id: "57", text: "Colombia", country_code: "+57"},
{iso_code:  "km", id: "269", text: "Comoros", country_code: "+269"},
{iso_code:  "cg", id: "242", text: "Congo", country_code: "+242"},
{iso_code:  "ck", id: "682", text: "Cook Islands", country_code: "+682"},
{iso_code:  "cr", id: "506", text: "Costa Rica", country_code: "+506"},
{iso_code:  "hr", id: "385", text: "Croatia", country_code: "+385"},
{iso_code:  "cu", id: "53", text: "Cuba", country_code: "+53"},
{iso_code:  "cy", id: "90", text: "Cyprus - North", country_code: "+90"},
{iso_code:  "cy", id: "357", text: "Cyprus - South", country_code: "+357"},
{iso_code:  "cz", id: "420", text: "Czech Republic", country_code: "+420"},
{iso_code:  "dk", id: "45", text: "Denmark", country_code: "+45"},
{iso_code:  "dj", id: "253", text: "Djibouti", country_code: "+253"},
{iso_code:  "dm", id: "1809", text: "Dominica", country_code: "+1809"},
{iso_code:  "do", id: "1809", text: "Dominican Republic", country_code: "+1809"},
{iso_code:  "ec", id: "593", text: "Ecuador", country_code: "+593"},
{iso_code:  "eg", id: "20", text: "Egypt", country_code: "+20"},
{iso_code:  "sv", id: "503", text: "El Salvador", country_code: "+503"},
{iso_code:  "gq", id: "240", text: "Equatorial Guinea", country_code: "+240"},
{iso_code:  "er", id: "291", text: "Eritrea", country_code: "+291"},
{iso_code:  "ee", id: "372", text: "Estonia", country_code: "+372"},
{iso_code:  "et", id: "251", text: "Ethiopia", country_code: "+251"},
{iso_code:  "fk", id: "500", text: "Falkland Islands", country_code: "+500"},
{iso_code:  "fo", id: "298", text: "Faroe Islands", country_code: "+298"},
{iso_code:  "fj", id: "679", text: "Fiji", country_code: "+679"},
{iso_code:  "fi", id: "358", text: "Finland", country_code: "+358"},
{iso_code:  "fr", id: "33", text: "France", country_code: "+33"},
{iso_code:  "gf", id: "594", text: "French Guiana", country_code: "+594"},
{iso_code:  "pf", id: "689", text: "French Polynesia", country_code: "+689"},
{iso_code:  "ga", id: "241", text: "Gabon", country_code: "+241"},
{iso_code:  "gm", id: "220", text: "Gambia", country_code: "+220"},
{iso_code:  "ge", id: "7880", text: "Georgia", country_code: "+7880"},
{iso_code:  "de", id: "49", text: "Germany", country_code: "+49"},
{iso_code:  "gh", id: "233", text: "Ghana", country_code: "+233"},
{iso_code:  "gi", id: "350", text: "Gibraltar", country_code: "+350"},
{iso_code:  "gr", id: "30", text: "Greece", country_code: "+30"},
{iso_code:  "gl", id: "299", text: "Greenland", country_code: "+299"},
{iso_code:  "gd", id: "1473", text: "Grenada", country_code: "+1473"},
{iso_code:  "gp", id: "590", text: "Guadeloupe", country_code: "+590"},
{iso_code:  "gu", id: "671", text: "Guam", country_code: "+671"},
{iso_code:  "gt", id: "502", text: "Guatemala", country_code: "+502"},
{iso_code:  "gn", id: "224", text: "Guinea", country_code: "+224"},
{iso_code:  "gw", id: "245", text: "Guinea - Bissau", country_code: "+245"},
{iso_code:  "gy", id: "592", text: "Guyana", country_code: "+592"},
{iso_code:  "ht", id: "509", text: "Haiti", country_code: "+509"},
{iso_code:  "hn", id: "504", text: "Honduras", country_code: "+504"},
{iso_code:  "hk", id: "852", text: "Hong Kong", country_code: "+852"},
{iso_code:  "hu", id: "36", text: "Hungary", country_code: "+36"},
{iso_code:  "is", id: "354", text: "Iceland", country_code: "+354"},
{iso_code:  "in", id: "91", text: "India", country_code: "+91"},
{iso_code:  "id", id: "62", text: "Indonesia", country_code: "+62"},
{iso_code:  "iq", id: "964", text: "Iraq", country_code: "+964"},
{iso_code:  "ir", id: "98", text: "Iran", country_code: "+98"},
{iso_code:  "ie", id: "353", text: "Ireland", country_code: "+353"},
{iso_code:  "il", id: "972", text: "Israel", country_code: "+972"},
{iso_code:  "it", id: "39", text: "Italy", country_code: "+39"},
{iso_code:  "jm", id: "1876", text: "Jamaica", country_code: "+1876"},
{iso_code:  "jp", id: "81", text: "Japan", country_code: "+81"},
{iso_code:  "jo", id: "962", text: "Jordan", country_code: "+962"},
{iso_code:  "kz", id: "7", text: "Kazakhstan", country_code: "+7"},
{iso_code:  "ke", id: "254", text: "Kenya", country_code: "+254"},
{iso_code:  "ki", id: "686", text: "Kiribati", country_code: "+686"},
{iso_code:  "kp", id: "850", text: "Korea - North", country_code: "+850"},
{iso_code:  "kr", id: "82", text: "Korea - South", country_code: "+82"},
{iso_code:  "kw", id: "965", text: "Kuwait", country_code: "+965"},
{iso_code:  "kg", id: "996", text: "Kyrgyzstan", country_code: "+996"},
{iso_code:  "la", id: "856", text: "Laos", country_code: "+856"},
{iso_code:  "lv", id: "371", text: "Latvia", country_code: "+371"},
{iso_code:  "lb", id: "961", text: "Lebanon", country_code: "+961"},
{iso_code:  "ls", id: "266", text: "Lesotho", country_code: "+266"},
{iso_code:  "lr", id: "231", text: "Liberia", country_code: "+231"},
{iso_code:  "ly", id: "218", text: "Libya", country_code: "+218"},
{iso_code:  "li", id: "417", text: "Liechtenstein", country_code: "+417"},
{iso_code:  "lt", id: "370", text: "Lithuania", country_code: "+370"},
{iso_code:  "lu", id: "352", text: "Luxembourg", country_code: "+352"},
{iso_code:  "mo", id: "853", text: "Macao", country_code: "+853"},
{iso_code:  "mk", id: "389", text: "Macedonia", country_code: "+389"},
{iso_code:  "mg", id: "261", text: "Madagascar", country_code: "+261"},
{iso_code:  "mw", id: "265", text: "Malawi", country_code: "+265"},
{iso_code:  "my", id: "60", text: "Malaysia", country_code: "+60"},
{iso_code:  "mv", id: "960", text: "Maldives", country_code: "+960"},
{iso_code:  "ml", id: "223", text: "Mali", country_code: "+223"},
{iso_code:  "mt", id: "356", text: "Malta", country_code: "+356"},
{iso_code:  "mh", id: "692", text: "Marshall Islands", country_code: "+692"},
{iso_code:  "mq", id: "596", text: "Martinique", country_code: "+596"},
{iso_code:  "mr", id: "222", text: "Mauritania", country_code: "+222"},
{iso_code:  "yt", id: "269", text: "Mayotte", country_code: "+269"},
{iso_code:  "mx", id: "52", text: "Mexico", country_code: "+52"},
{iso_code:  "fm", id: "691", text: "Micronesia", country_code: "+691"},
{iso_code:  "md", id: "373", text: "Moldova", country_code: "+373"},
{iso_code:  "mc", id: "377", text: "Monaco", country_code: "+377"},
{iso_code:  "mn", id: "976", text: "Mongolia", country_code: "+976"},
{iso_code:  "ms", id: "1664", text: "Montserrat", country_code: "+1664"},
{iso_code:  "ma", id: "212", text: "Morocco", country_code: "+212"},
{iso_code:  "mz", id: "258", text: "Mozambique", country_code: "+258"},
{iso_code:  "mn", id: "95", text: "Myanmar", country_code: "+95"},
{iso_code:  "na", id: "264", text: "Namibia", country_code: "+264"},
{iso_code:  "nr", id: "674", text: "Nauru", country_code: "+674"},
{iso_code:  "np", id: "977", text: "Nepal", country_code: "+977"},
{iso_code:  "nl", id: "31", text: "Netherlands", country_code: "+31"},
{iso_code:  "nc", id: "687", text: "New Caledonia", country_code: "+687"},
{iso_code:  "nz", id: "64", text: "New Zealand", country_code: "+64"},
{iso_code:  "ni", id: "505", text: "Nicaragua", country_code: "+505"},
{iso_code:  "ne", id: "227", text: "Niger", country_code: "+227"},
{iso_code:  "ng", id: "234", text: "Nigeria", country_code: "+234"},
{iso_code:  "nu", id: "683", text: "Niue", country_code: "+683"},
{iso_code:  "nf", id: "672", text: "Norfolk Islands", country_code: "+672"},
{iso_code:  "np", id: "670", text: "Northern Marianas", country_code: "+670"},
{iso_code:  "no", id: "47", text: "Norway", country_code: "+47"},
{iso_code:  "om", id: "968", text: "Oman", country_code: "+968"},
{iso_code:  "pk", id: "92", text: "Pakistan", country_code: "+92"},
{iso_code:  "pw", id: "680", text: "Palau", country_code: "+680"},
{iso_code:  "pa", id: "507", text: "Panama", country_code: "+507"},
{iso_code:  "pg", id: "675", text: "Papua New Guinea", country_code: "+675"},
{iso_code:  "py", id: "595", text: "Paraguay", country_code: "+595"},
{iso_code:  "pe", id: "51", text: "Peru", country_code: "+51"},
{iso_code:  "ph", id: "63", text: "Philippines", country_code: "+63"},
{iso_code:  "pl", id: "48", text: "Poland", country_code: "+48"},
{iso_code:  "pt", id: "351", text: "Portugal", country_code: "+351"},
{iso_code:  "pr", id: "1787", text: "Puerto Rico", country_code: "+1787"},
{iso_code:  "qa", id: "974", text: "Qatar", country_code: "+974"},
{iso_code:  "re", id: "262", text: "Reunion", country_code: "+262"},
{iso_code:  "ro", id: "40", text: "Romania", country_code: "+40"},
{iso_code:  "ru", id: "7", text: "Russia", country_code: "+7"},
{iso_code:  "rw", id: "250", text: "Rwanda", country_code: "+250"},
{iso_code:  "sm", id: "378", text: "San Marino", country_code: "+378"},
{iso_code:  "st", id: "239", text: "Sao Tome & Principe", country_code: "+239"},
{iso_code:  "sa", id: "966", text: "Saudi Arabia", country_code: "+966"},
{iso_code:  "sn", id: "221", text: "Senegal", country_code: "+221"},
{iso_code:  "rs", id: "381", text: "Serbia", country_code: "+381"},
{iso_code:  "sc", id: "248", text: "Seychelles", country_code: "+248"},
{iso_code:  "sl", id: "232", text: "Sierra Leone", country_code: "+232"},
{iso_code:  "sg", id: "65", text: "Singapore", country_code: "+65"},
{iso_code:  "sk", id: "421", text: "Slovak Republic", country_code: "+421"},
{iso_code:  "si", id: "386", text: "Slovenia", country_code: "+386"},
{iso_code:  "sb", id: "677", text: "Solomon Islands", country_code: "+677"},
{iso_code:  "so", id: "252", text: "Somalia", country_code: "+252"},
{iso_code:  "za", id: "27", text: "South Africa", country_code: "+27"},
{iso_code:  "es", id: "34", text: "Spain", country_code: "+34"},
{iso_code:  "lk", id: "94", text: "Sri Lanka", country_code: "+94"},
{iso_code:  "sh", id: "290", text: "St. Helena", country_code: "+290"},
{iso_code:  "kn", id: "1869", text: "St. Kitts", country_code: "+1869"},
{iso_code:  "sc", id: "1758", text: "St. Lucia", country_code: "+1758"},
{iso_code:  "sr", id: "597", text: "Suriname", country_code: "+597"},
{iso_code:  "sd", id: "249", text: "Sudan", country_code: "+249"},
{iso_code:  "sz", id: "268", text: "Swaziland", country_code: "+268"},
{iso_code:  "se", id: "46", text: "Sweden", country_code: "+46"},
{iso_code:  "ch", id: "41", text: "Switzerland", country_code: "+41"},
{iso_code:  "sy", id: "963", text: "Syria", country_code: "+963"},
{iso_code:  "tw", id: "886", text: "Taiwan", country_code: "+886"},
{iso_code:  "tj", id: "992", text: "Tajikistan", country_code: "+992"},
{iso_code:  "th", id: "66", text: "Thailand", country_code: "+66"},
{iso_code:  "tg", id: "228", text: "Togo", country_code: "+228"},
{iso_code:  "to", id: "676", text: "Tonga", country_code: "+676"},
{iso_code:  "tt", id: "1868", text: "Trinidad & Tobago", country_code: "+1868"},
{iso_code:  "tn", id: "216", text: "Tunisia", country_code: "+216"},
{iso_code:  "tr", id: "90", text: "Turkey", country_code: "+90"},
{iso_code:  "tm", id: "993", text: "Turkmenistan", country_code: "+993"},
{iso_code:  "tc", id: "1649", text: "Turks & Caicos Islands", country_code: "+1649"},
{iso_code:  "tv", id: "688", text: "Tuvalu", country_code: "+688"},
{iso_code:  "ug", id: "256", text: "Uganda", country_code: "+256"},
{iso_code:  "ua", id: "380", text: "Ukraine", country_code: "+380"},
{iso_code:  "ae", id: "971", text: "United Arab Emirates", country_code: "+971"},
{iso_code:  "uy", id: "598", text: "Uruguay", country_code: "+598"},
{iso_code:  "uz", id: "998", text: "Uzbekistan", country_code: "+998"},
{iso_code:  "vu", id: "678", text: "Vanuatu", country_code: "+678"},
{iso_code:  "va", id: "379", text: "Vatican City", country_code: "+379"},
{iso_code:  "ve", id: "58", text: "Venezuela", country_code: "+58"},
{iso_code:  "vn", id: "84", text: "Vietnam", country_code: "+84"},
{iso_code:  "vg", id: "1", text: "Virgin Islands - British", country_code: "+1"},
{iso_code:  "vi", id: "1", text: "Virgin Islands - US", country_code: "+1"},
{iso_code:  "wf", id: "681", text: "Wallis & Futuna", country_code: "+681"},
{iso_code:  "ye", id: "969", text: "Yemen (North)", country_code: "+969"},
{iso_code:  "ye", id: "967", text: "Yemen (South)", country_code: "+967"},
{iso_code:  "zm", id: "260", text: "Zambia", country_code: "+260"},
{iso_code:  "zw", id: "263", text: "Zimbabwe", country_code: "+263"}
];
