<?php

namespace App\Http\Requests\Cabinet;

use App\Http\Requests\Cabinet\API\v1\BaseRequest;
use App\Models\CryptoAccountDetail;
use Illuminate\Validation\Rule;

class AddWalletRequest extends \App\Http\Requests\BaseRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $allowedCoinsForAccount = array_keys(CryptoAccountDetail::getAllowedCoinsForAccount());

        return [
            'cryptocurrency' => ['required', Rule::in($allowedCoinsForAccount)],
        ];
    }

    public function getValidatorInstance()
    {
        $this->formatCryptocurrency();
        return parent::getValidatorInstance(); // TODO: Change the autogenerated stub
    }

    protected function formatCryptocurrency()
    {
        $this->merge([
            'cryptocurrency' => strtolower($this->cryptocurrency),
        ]);
    }
}
