<?php

use App\Models\Country;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class AddCountriesToCountryTable extends Migration
{
    const NOT_BANNED_COUNTRIES = [
        "us" => "1",
        "gb" => "44",
        "dz" => "213",
        "ad" => "376",
        "ao" => "244",
        "ai" => "1264",
        "ag" => "1268",
        "ar" => "54",
        "am" => "374",
        "aw" => "297",
        "au" => "61",
        "at" => "43",
        "az" => "994",
        "bs" => "1242",
        "bh" => "973",
        "bd" => "880",
        "bb" => "1246",
        "by" => "375",
        "be" => "32",
        "bz" => "501",
        "bj" => "229",
        "bm" => "1441",
        "bt" => "975",
        "bo" => "591",
        "ba" => "387",
        "bw" => "267",
        "br" => "55",
        "bn" => "673",
        "bg" => "359",
        "bf" => "226",
        "bi" => "257",
        "kh" => "855",
        "cm" => "237",
        "ca" => "1",
        "cv" => "238",
        "ky" => "1345",
        "cf" => "236",
        "cl" => "56",
        "cn" => "86",
        "co" => "57",
        "km" => "269",
        "cg" => "242",
        "ck" => "682",
        "cr" => "506",
        "hr" => "385",
        "cu" => "53",
        "cy" => [
            "357", "90"
        ],
        "cz" => "420",
        "dk" => "45",
        "dj" => "253",
        "dm" => "1809",
        "do" => "1809",
        "ec" => "593",
        "eg" => "20",
        "sv" => "503",
        "gq" => "240",
        "er" => "291",
        "ee" => "372",
        "et" => "251",
        "fk" => "500",
        "fo" => "298",
        "fj" => "679",
        "fi" => "358",
        "fr" => "33",
        "gf" => "594",
        "pf" => "689",
        "ga" => "241",
        "gm" => "220",
        "ge" => "7880",
        "de" => "49",
        "gh" => "233",
        "gi" => "350",
        "gr" => "30",
        "gl" => "299",
        "gd" => "1473",
        "gp" => "590",
        "gu" => "671",
        "gt" => "502",
        "gn" => "224",
        "gw" => "245",
        "gy" => "592",
        "ht" => "509",
        "hn" => "504",
        "hk" => "852",
        "hu" => "36",
        "is" => "354",
        "in" => "91",
        "id" => "62",
        "iq" => "964",
        "ir" => "98",
        "ie" => "353",
        "il" => "972",
        "it" => "39",
        "jm" => "1876",
        "jp" => "81",
        "jo" => "962",
        "kz" => "7",
        "ke" => "254",
        "ki" => "686",
        "kp" => "850",
        "kr" => "82",
        "kw" => "965",
        "kg" => "996",
        "la" => "856",
        "lv" => "371",
        "lb" => "961",
        "ls" => "266",
        "lr" => "231",
        "ly" => "218",
        "li" => "417",
        "lt" => "370",
        "lu" => "352",
        "mo" => "853",
        "mk" => "389",
        "mg" => "261",
        "mw" => "265",
        "my" => "60",
        "mv" => "960",
        "ml" => "223",
        "mt" => "356",
        "mh" => "692",
        "mq" => "596",
        "mr" => "222",
        "yt" => "269",
        "mx" => "52",
        "fm" => "691",
        "md" => "373",
        "mc" => "377",
        "ms" => "1664",
        "ma" => "212",
        "mz" => "258",
        "mn" => [
            "95", "976"
        ],
        "na" => "264",
        "nr" => "674",
        "nl" => "31",
        "nc" => "687",
        "nz" => "64",
        "ni" => "505",
        "ne" => "227",
        "ng" => "234",
        "nu" => "683",
        "nf" => "672",
        "np" => [
            "670", "977"
        ],
        "no" => "47",
        "om" => "968",
        "pk" => "92",
        "pw" => "680",
        "pa" => "507",
        "pg" => "675",
        "py" => "595",
        "pe" => "51",
        "ph" => "63",
        "pl" => "48",
        "pt" => "351",
        "pr" => "1787",
        "qa" => "974",
        "re" => "262",
        "ro" => "40",
        "ru" => "7",
        "rw" => "250",
        "sm" => "378",
        "st" => "239",
        "sa" => "966",
        "sn" => "221",
        "rs" => "381",
        "sc" => [
            "248", "1758"
        ],
        "sl" => "232",
        "sg" => "65",
        "sk" => "421",
        "si" => "386",
        "sb" => "677",
        "so" => "252",
        "za" => "27",
        "es" => "34",
        "lk" => "94",
        "sh" => "290",
        "kn" => "1869",
        "sr" => "597",
        "sd" => "249",
        "sz" => "268",
        "se" => "46",
        "ch" => "41",
        "sy" => "963",
        "tw" => "886",
        "tj" => "992",
        "th" => "66",
        "tg" => "228",
        "to" => "676",
        "tt" => "1868",
        "tn" => "216",
        "tr" => "90",
        "tm" => "993",
        "tc" => "1649",
        "tv" => "688",
        "ug" => "256",
        "ua" => "380",
        "ae" => "971",
        "uy" => "598",
        "uz" => "998",
        "vu" => "678",
        "va" => "379",
        "ve" => "58",
        "vn" => "84",
        "vg" => "1",
        "vi" => "1",
        "wf" => "681",
        "ye" => [
            "969", "967"
        ],
        "zm" => "260",
        "zw" => "263",
    ];

    const ALL_COUNTRIES =
        [
            "AF" => "Afghanistan",
            "AL" => "Albania",
            "DZ" => "Algeria",
            "AS" => "American Samoa",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AI" => "Anguilla",
            "AQ" => "Antarctica",
            "AG" => "Antigua and Barbuda",
            "AR" => "Argentina",
            "AM" => "Armenia",
            "AW" => "Aruba",
            "AU" => "Australia",
            "AT" => "Austria",
            "AZ" => "Azerbaijan",
            "BS" => "Bahamas",
            "BH" => "Bahrain",
            "BD" => "Bangladesh",
            "BB" => "Barbados",
            "BY" => "Belarus",
            "BE" => "Belgium",
            "BZ" => "Belize",
            "BJ" => "Benin",
            "BM" => "Bermuda",
            "BT" => "Bhutan",
            "BO" => "Bolivia",
            "BA" => "Bosnia and Herzegovina",
            "BW" => "Botswana",
            "BV" => "Bouvet Island",
            "BR" => "Brazil",
            "IO" => "British Indian Ocean Territory",
            "BN" => "Brunei Darussalam",
            "BG" => "Bulgaria",
            "BF" => "Burkina Faso",
            "BI" => "Burundi",
            "KH" => "Cambodia",
            "CM" => "Cameroon",
            "CA" => "Canada",
            "CV" => "Cape Verde",
            "KY" => "Cayman Islands",
            "CF" => "Central African Republic",
            "TD" => "Chad",
            "CL" => "Chile",
            "CN" => "China",
            "CX" => "Christmas Island",
            "CC" => "Cocos (Keeling) Islands",
            "CO" => "Colombia",
            "KM" => "Comoros",
            "CG" => "Congo",
            "CD" => "Congo, the Democratic Republic of the",
            "CK" => "Cook Islands",
            "CR" => "Costa Rica",
            "CI" => "Cote D'Ivoire",
            "HR" => "Croatia",
            "CU" => "Cuba",
            "CY" => "Cyprus",
            "CZ" => "Czech Republic",
            "DK" => "Denmark",
            "DJ" => "Djibouti",
            "DM" => "Dominica",
            "DO" => "Dominican Republic",
            "EC" => "Ecuador",
            "EG" => "Egypt",
            "SV" => "El Salvador",
            "GQ" => "Equatorial Guinea",
            "ER" => "Eritrea",
            "EE" => "Estonia",
            "ET" => "Ethiopia",
            "FK" => "Falkland Islands (Malvinas)",
            "FO" => "Faroe Islands",
            "FJ" => "Fiji",
            "FI" => "Finland",
            "FR" => "France",
            "GF" => "French Guiana",
            "PF" => "French Polynesia",
            "TF" => "French Southern Territories",
            "GA" => "Gabon",
            "GM" => "Gambia",
            "GE" => "Georgia",
            "DE" => "Germany",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GR" => "Greece",
            "GL" => "Greenland",
            "GD" => "Grenada",
            "GP" => "Guadeloupe",
            "GU" => "Guam",
            "GT" => "Guatemala",
            "GN" => "Guinea",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HT" => "Haiti",
            "HM" => "Heard Island and Mcdonald Islands",
            "VA" => "Holy See (Vatican City State)",
            "HN" => "Honduras",
            "HK" => "Hong Kong",
            "HU" => "Hungary",
            "IS" => "Iceland",
            "IN" => "India",
            "ID" => "Indonesia",
            "IR" => "Iran, Islamic Republic of",
            "IQ" => "Iraq",
            "IE" => "Ireland",
            "IL" => "Israel",
            "IT" => "Italy",
            "JM" => "Jamaica",
            "JP" => "Japan",
            "JO" => "Jordan",
            "KZ" => "Kazakhstan",
            "KE" => "Kenya",
            "KI" => "Kiribati",
            "KP" => "Korea, Democratic People's Republic of",
            "KR" => "Korea, Republic of",
            "KW" => "Kuwait",
            "KG" => "Kyrgyzstan",
            "LA" => "Lao People's Democratic Republic",
            "LV" => "Latvia",
            "LB" => "Lebanon",
            "LS" => "Lesotho",
            "LR" => "Liberia",
            "LY" => "Libyan Arab Jamahiriya",
            "LI" => "Liechtenstein",
            "LT" => "Lithuania",
            "LU" => "Luxembourg",
            "MO" => "Macao",
            "MK" => "Macedonia, the Former Yugoslav Republic of",
            "MG" => "Madagascar",
            "MW" => "Malawi",
            "MY" => "Malaysia",
            "MV" => "Maldives",
            "ML" => "Mali",
            "MT" => "Malta",
            "MH" => "Marshall Islands",
            "MQ" => "Martinique",
            "MR" => "Mauritania",
            "MU" => "Mauritius",
            "YT" => "Mayotte",
            "MX" => "Mexico",
            "FM" => "Micronesia, Federated States of",
            "MD" => "Moldova, Republic of",
            "MC" => "Monaco",
            "MN" => "Mongolia",
            "MS" => "Montserrat",
            "MA" => "Morocco",
            "MZ" => "Mozambique",
            "MM" => "Myanmar",
            "NA" => "Namibia",
            "NR" => "Nauru",
            "NP" => "Nepal",
            "NL" => "Netherlands",
            "AN" => "Netherlands Antilles",
            "NC" => "New Caledonia",
            "NZ" => "New Zealand",
            "NI" => "Nicaragua",
            "NE" => "Niger",
            "NG" => "Nigeria",
            "NU" => "Niue",
            "NF" => "Norfolk Island",
            "MP" => "Northern Mariana Islands",
            "NO" => "Norway",
            "OM" => "Oman",
            "PK" => "Pakistan",
            "PW" => "Palau",
            "PS" => "Palestinian Territory, Occupied",
            "PA" => "Panama",
            "PG" => "Papua New Guinea",
            "PY" => "Paraguay",
            "PE" => "Peru",
            "PH" => "Philippines",
            "PN" => "Pitcairn",
            "PL" => "Poland",
            "PT" => "Portugal",
            "PR" => "Puerto Rico",
            "QA" => "Qatar",
            "RE" => "Reunion",
            "RO" => "Romania",
            "RU" => "Russian Federation",
            "RW" => "Rwanda",
            "SH" => "Saint Helena",
            "KN" => "Saint Kitts and Nevis",
            "LC" => "Saint Lucia",
            "PM" => "Saint Pierre and Miquelon",
            "VC" => "Saint Vincent and the Grenadines",
            "WS" => "Samoa",
            "SM" => "San Marino",
            "ST" => "Sao Tome and Principe",
            "SA" => "Saudi Arabia",
            "SN" => "Senegal",
            "RS" => "Republic of Serbia",
            "CS" => "Serbia and Montenegro",
            "SC" => "Seychelles",
            "SL" => "Sierra Leone",
            "SG" => "Singapore",
            "SK" => "Slovakia",
            "SI" => "Slovenia",
            "SB" => "Solomon Islands",
            "SO" => "Somalia",
            "ZA" => "South Africa",
            "GS" => "South Georgia and the South Sandwich Islands",
            "ES" => "Spain",
            "LK" => "Sri Lanka",
            "SD" => "Sudan",
            "SR" => "Suriname",
            "SJ" => "Svalbard and Jan Mayen",
            "SZ" => "Swaziland",
            "SE" => "Sweden",
            "CH" => "Switzerland",
            "SY" => "Syrian Arab Republic",
            "TW" => "Taiwan, Province of China",
            "TJ" => "Tajikistan",
            "TZ" => "Tanzania, United Republic of",
            "TH" => "Thailand",
            "TL" => "Timor-Leste",
            "TG" => "Togo",
            "TK" => "Tokelau",
            "TO" => "Tonga",
            "TT" => "Trinidad and Tobago",
            "TN" => "Tunisia",
            "TR" => "Turkey",
            "TM" => "Turkmenistan",
            "TC" => "Turks and Caicos Islands",
            "TV" => "Tuvalu",
            "UG" => "Uganda",
            "UA" => "Ukraine",
            "AE" => "United Arab Emirates",
            "GB" => "United Kingdom",
            "US" => "United States",
            "UM" => "United States Minor Outlying Islands",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VU" => "Vanuatu",
            "VE" => "Venezuela",
            "VN" => "Viet Nam",
            "VG" => "Virgin Islands, British",
            "VI" => "Virgin Islands, U.s.",
            "WF" => "Wallis and Futuna",
            "EH" => "Western Sahara",
            "YE" => "Yemen",
            "ZM" => "Zambia",
            "ZW" => "Zimbabwe"
        ];



    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        foreach (self::ALL_COUNTRIES as $code => $countryName) {
            $country = new Country();
            $country->code = Str::lower($code);
            $country->name = $countryName;
            if (array_key_exists($country->code, self::NOT_BANNED_COUNTRIES)) {
                $country->is_banned = false;
                $countryPhoneCode = self::NOT_BANNED_COUNTRIES[$country->code];
                if (!is_array($countryPhoneCode)) {
                    $countryPhoneCode = [$countryPhoneCode];
                }
                $country->phone_code = $countryPhoneCode;
            } else {
                $country->is_banned = true;
                $country->phone_code = null;
            }
            $country->save();
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
       Country::truncate();
    }
}
